---
- hosts: all
  tasks:
    - name: copy checkLogstash Script file from work station to remote stitcher node
      copy:
        src: checkLogstash.sh 
        dest: /etc/cron.hourly/
        owner: root
        group: root
        mode: 0755
